name: Maven Deploy (Dev)

on:
  push:
    branches:
      - 'main' # Build the latest develop-SNAPSHOT
    paths:
      - 'src/**'
      - 'pom.xml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: 14
          
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[{ "id": "gh-releases", "username": "gh-actions", "password": "${{ secrets.DEPLOY_PASS }}" }, { "id": "gh-snapshots", "username": "gh-actions", "password": "${{ secrets.DEPLOY_PASS }}" }]'
      
      - name: Cache Maven Packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
                      
      - name: Verify with Maven
        run: mvn -B verify
      
      - name: Publish Package
        run: mvn -B deploy
