name: Maven Deploy (Prod)

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
        
      - name: Verify with Maven
        run: mvn -B verify

      - name: Configure GIT
        run: git config --global user.email "gh-actions@fuchss.org" &&  git config --global user.name "CI"
        
      - name: Publish Package
        run: mvn -B deploy
        env:
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
