name: Maven Deploy (Prod)

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "gh-releases", "username": "gh-actions", "password": "${{ secrets.DEPLOY_PASS }}" }, { "id": "gh-snapshots", "username": "gh-actions", "password": "${{ secrets.DEPLOY_PASS }}" }]'
        
      - name: Verify with Maven
        run: mvn -B verify
      
      - name: Publish Package
        run: mvn -B deploy
